
---
server:
  port: 8080
spring:
  profiles:
    active: prod
---
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8082
spring:
  profiles: prod
---
#person:
   # lastName: zhangsan
   # boss: false
  #  birth: 2019/2/11
   # maps: {k1: v1,k2: 12}
   # lists: [1,2,3,4]
   # dog:
   #   name: xiaobai
   #   age: 3
    #  age: 22